---
abstract: 'inline packages easily'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: thanks
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  thanks:
    file: lib/thanks.pm
    version: 0.005
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/thanks/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=thanks
  homepage: https://metacpan.org/release/thanks
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-thanks
version: 0.005
