---
abstract: "no thanks, I don't want that module"
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: thanks
name: thanks
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=thanks
  homepage: https://metacpan.org/release/thanks
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-thanks
version: 0.001
